name: Continuous Integration

on:
  pull_request:
  push:
    branches: [ "main"]
  workflow_dispatch:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '21'
      JAR_PATH: "target/surefire-reports"

    steps:
      - name: Baixar código
        uses: actions/checkout@v6

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Versão do java
        run: java -version


      - name: Versão do mvn
        run: mvn -version


      - name: Limpar build anterior
        run: mvn clean

      - name: Compilar projeto
        run: mvn compile

      - name: Executar testes
        run: mvn test

      - name: Empacotar aplicação
        run: mvn package -DskipTests

      - name: Salvar relatórios de teste
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-de-teste
          path: ${{env.JAR_PATH}}

      - name: Salvar arquivo JAR
        if: always()
        uses: actions/upload-artifact@v4
        with:
         name: build-jar
         path: target/*.jar

      - name: Finalizar workflow
        if: always()
        run: echo "Workflow finalizado"